/*
 * The MIT License
 *
 * Copyright 2025 armando.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.armandorivera.psimessageapp.Views;

import com.armandorivera.psimessageapp.Client;
import com.armandorivera.psimessageapp.MessageService;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.cert.X509Certificate;
import java.util.Base64;

import com.armandorivera.psimessageapp.Client;
import com.armandorivera.psimessageapp.CryptoMode;

import java.security.cert.X509Certificate;

/**
 *
 * @author armando
 */
public class ClientFrame extends javax.swing.JInternalFrame {

    private final Client client;

    public ClientFrame(Client client) {
        this.client = client;
        initComponents();
        setupClientInfo();

        // 👇 Aquí SI puedes escribir, no está protegido
        // Cuando cambie la selección del destinatario:
        destUsersList.addActionListener(evt -> verifySelectedRecipientAndUpdateAlert());

        // Cuando se presione el botón Update:
        updateDestListButton.addActionListener(evt -> refreshDestUsersList());
    }

    private void setupClientInfo() {
        usernameLabel.setText(client.getName());
        refreshDestUsersList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        destLabel = new javax.swing.JLabel();
        destUsersList = new javax.swing.JComboBox<>();
        updateDestListButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        alertLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        certButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        usernameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Armando");

        destLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        destLabel.setText("Destinatario:");

        destUsersList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        updateDestListButton.setText("Update");
        updateDestListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDestListButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Mensajes recibidos:");

        jScrollPane1.setViewportView(jTextPane1);

        alertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alertLabel.setText("Alerta de mensaje");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Mensaje para enviar:");

        certButton.setText("Ver certificado");
        certButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(destLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destUsersList, 0, 229, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateDestListButton))
                    .addComponent(alertLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(certButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destLabel)
                    .addComponent(destUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateDestListButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alertLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addComponent(certButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void certButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certButtonActionPerformed
        java.security.cert.X509Certificate cert = client.getCertificate();

        // 1) Construir texto informativo + certificado en PEM
        StringBuilder sb = new StringBuilder();
        sb.append("=== Información del certificado ===\n");
        sb.append("Sujeto: ").append(cert.getSubjectX500Principal().getName()).append("\n");
        sb.append("Emisor: ").append(cert.getIssuerX500Principal().getName()).append("\n");
        sb.append("Serie (hex): ").append(cert.getSerialNumber().toString(16)).append("\n");
        sb.append("Válido desde: ").append(cert.getNotBefore()).append("\n");
        sb.append("Válido hasta: ").append(cert.getNotAfter()).append("\n\n");

        try {
            String pemCert = toPemCertificate(cert);
            String pemPrivate = toPemPrivateKey(client.getKeyPair().getPrivate());
            String pemPublic = toPemPublicKey(client.getKeyPair().getPublic());

            sb.append("=== CERTIFICADO (PEM) ===\n");
            sb.append(pemCert).append("\n\n");
            sb.append("=== LLAVE PÚBLICA (PEM) ===\n");
            sb.append(pemPublic).append("\n\n");
            sb.append("=== LLAVE PRIVADA (PEM) ===\n");
            sb.append(pemPrivate).append("\n");

            // 2) Mostrar en una ventana con JTextArea (texto seleccionable y copiable)
            showCertificateDialog(sb.toString());

            // 3) Guardar archivos en disco
            saveCertAndKeysToFiles(cert, client);
        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al procesar/generar archivos del certificado: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_certButtonActionPerformed

    private void showCertificateDialog(String text) {
        javax.swing.JTextArea textArea = new javax.swing.JTextArea(text);
        textArea.setEditable(false);            // no se puede modificar
        textArea.setLineWrap(false);            // no forzar salto de línea
        textArea.setCaretPosition(0);           // ir al inicio

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);

        javax.swing.JDialog dialog = new javax.swing.JDialog(
                javax.swing.SwingUtilities.getWindowAncestor(this),
                "Certificado de " + client.getName(),
                java.awt.Dialog.ModalityType.MODELESS
        );
        dialog.getContentPane().add(scrollPane);
        dialog.setSize(700, 500);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }


    private void updateDestListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDestListButtonActionPerformed
        refreshDestUsersList();
    }//GEN-LAST:event_updateDestListButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String destName = (String) destUsersList.getSelectedItem();
        if (destName == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Selecciona un destinatario.", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String message = jTextField1.getText().trim();
        if (message.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Escribe un mensaje.", "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Enviar mensaje usando AES + RSA
        MessageService.sendMessage(client, destName, message);
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void refreshDestUsersList() {
        destUsersList.removeAllItems();
        for (Client c : MainFrame.getClients()) {
            if (!c.getName().equals(client.getName())) {
                destUsersList.addItem(c.getName());
            }
        }
    }

    public void receiveMessage(String from, String plaintext, String ctBase64) {
        String prev = jTextPane1.getText();
        String newMsg = "[" + from + "]: " + plaintext + "\n";
        jTextPane1.setText(prev + newMsg);
        alertLabel.setText("Nuevo mensaje de " + from);
    }

    private void verifySelectedRecipientAndUpdateAlert() {
        String destName = (String) destUsersList.getSelectedItem();
        if (destName == null || destName.isEmpty()) {
            alertLabel.setText("Selecciona un destinatario para verificar su certificado.");
            return;
        }

        Client recipient = MainFrame.getClientByName(destName);
        if (recipient == null) {
            alertLabel.setText("No se encontró el cliente seleccionado.");
            return;
        }

        java.security.cert.X509Certificate cert = recipient.getCertificate();
        try {
            // 1. Verificar fechas
            cert.checkValidity();

            // 2. Verificar firma con la CA MSN INAOE
            cert.verify(MainFrame.getCA().getCaPublicKey());

            // 3. Verificar que esté en la lista de confianza
            if (!MainFrame.getCA().isTrusted(cert)) {
                alertLabel.setText("Advertencia: certificado no está en la lista de confianza.");
                return;
            }

            // 4. Mensaje según el modo criptográfico
            CryptoMode mode = recipient.getMode();
            if (mode == CryptoMode.CLASSIC) {
                alertLabel.setText("Certificado seguro. Se utilizará el método clásico (RSA + AES).");
            } else if (mode == CryptoMode.HYBRID_PQ) {
                alertLabel.setText("Certificado seguro. Se utilizará el método híbrido post-cuántico (Kyber + RSA).");
            } else {
                alertLabel.setText("Certificado seguro. Modo criptográfico desconocido.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            alertLabel.setText("Advertencia: certificado NO válido o no confiable.");
        }
    }

    private String toPemCertificate(X509Certificate cert) throws Exception {
        byte[] encoded = cert.getEncoded();
        String b64 = Base64.getMimeEncoder(64, "\n".getBytes())
                .encodeToString(encoded);
        return "-----BEGIN CERTIFICATE-----\n"
                + b64
                + "\n-----END CERTIFICATE-----";
    }

    private String toPemPrivateKey(PrivateKey privateKey) {
        byte[] encoded = privateKey.getEncoded(); // PKCS#8
        String b64 = Base64.getMimeEncoder(64, "\n".getBytes())
                .encodeToString(encoded);
        return "-----BEGIN PRIVATE KEY-----\n"
                + b64
                + "\n-----END PRIVATE KEY-----";
    }

    private String toPemPublicKey(PublicKey publicKey) {
        byte[] encoded = publicKey.getEncoded(); // X.509 SubjectPublicKeyInfo
        String b64 = Base64.getMimeEncoder(64, "\n".getBytes())
                .encodeToString(encoded);
        return "-----BEGIN PUBLIC KEY-----\n"
                + b64
                + "\n-----END PUBLIC KEY-----";
    }

    private void saveCertAndKeysToFiles(X509Certificate cert, Client client) throws Exception {
        // Carpeta "certs" dentro del directorio actual del proyecto
        String baseDir = System.getProperty("user.dir") + File.separator + "certs";
        File dir = new File(baseDir);
        if (!dir.exists()) {
            dir.mkdirs();
        }

        String safeName = client.getName().replaceAll("[^a-zA-Z0-9._-]", "_");

        File certFile = new File(dir, safeName + "_cert.pem");
        File privFile = new File(dir, safeName + "_private_key.pem");
        File pubFile = new File(dir, safeName + "_public_key.pem");

        String pemCert = toPemCertificate(cert);
        String pemPrivate = toPemPrivateKey(client.getKeyPair().getPrivate());
        String pemPublic = toPemPublicKey(client.getKeyPair().getPublic());

        Files.writeString(certFile.toPath(), pemCert, StandardCharsets.UTF_8);
        Files.writeString(privFile.toPath(), pemPrivate, StandardCharsets.UTF_8);
        Files.writeString(pubFile.toPath(), pemPublic, StandardCharsets.UTF_8);

        javax.swing.JOptionPane.showMessageDialog(this,
                "Archivos guardados en:\n"
                + certFile.getParentFile().getAbsolutePath(),
                "Certificado guardado",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertLabel;
    private javax.swing.JButton certButton;
    private javax.swing.JLabel destLabel;
    private javax.swing.JComboBox<String> destUsersList;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton updateDestListButton;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
