/*
 * The MIT License
 *
 * Copyright 2025 armando.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.armandorivera.psimessageapp.Views;

import com.armandorivera.psimessageapp.CertificateAuthority;
import com.armandorivera.psimessageapp.Client;
import com.armandorivera.psimessageapp.CryptoMode;
import java.awt.Color;

/**
 *
 * @author armando
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private javax.swing.JDesktopPane desktopPane;

    public MainFrame() {
        initComponents();

        setup();
        // Configuración de la pantalla
        setExtendedState(MainFrame.MAXIMIZED_BOTH);
    }

    private static final CertificateAuthority CA = new CertificateAuthority();
    private static final java.util.List<Client> CLIENTS = new java.util.ArrayList<>();
    private static final java.util.Map<Client, ClientFrame> CLIENT_FRAMES = new java.util.HashMap<>();

    public static CertificateAuthority getCA() {
        return CA;
    }

    public static java.util.List<Client> getClients() {
        return CLIENTS;
    }

    public static void addClient(Client c) {
        CLIENTS.add(c);
    }

    public static void registerClientFrame(Client client, ClientFrame frame) {
        CLIENT_FRAMES.put(client, frame);
    }

    public static ClientFrame getFrameForClient(Client client) {
        return CLIENT_FRAMES.get(client);
    }

    public static Client getClientByName(String name) {
        for (Client c : CLIENTS) {
            if (c.getName().equals(name)) {
                return c;
            }
        }
        return null;
    }

    private void setup() {
        desktopPane = new javax.swing.JDesktopPane();
        desktopPane.setBackground(Color.WHITE);

        getContentPane().add(desktopPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }

    public static void deliverMessage(Client recipient, String fromName, String plaintext, String ctBase64) {
        ClientFrame frame = CLIENT_FRAMES.get(recipient);
        if (frame != null) {
            frame.receiveMessage(fromName, plaintext, ctBase64);
        } else {
            System.err.println("No hay frame para el cliente: " + recipient.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addClientButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        addClientButton.setText("Agregar cliente");
        addClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientButtonActionPerformed(evt);
            }
        });
        jMenu1.add(addClientButton);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientButtonActionPerformed
        String fullName = javax.swing.JOptionPane.showInputDialog(this, "Nombre completo del cliente:");
        if (fullName == null) {
            return;
        }
        fullName = fullName.trim();
        if (fullName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.",
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        Object[] options = {"Clásico (RSA + AES)", "Post-cuántico / Híbrido (Kyber + RSA)"};
        int choice = javax.swing.JOptionPane.showOptionDialog(
                this,
                "Selecciona el tipo de esquema criptográfico para este cliente:",
                "Modo criptográfico",
                javax.swing.JOptionPane.DEFAULT_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        if (choice == javax.swing.JOptionPane.CLOSED_OPTION) {
            return;
        }

        CryptoMode mode = (choice == 0) ? CryptoMode.CLASSIC : CryptoMode.HYBRID_PQ;

        try {
            // 1) Crear cliente (claves + cert + archivos)
            Client client = MainFrame.getCA().registerNewClient(fullName, mode);
            MainFrame.addClient(client);

            // 2) Crear su frame
            ClientFrame clientFrame = new ClientFrame(client);
            desktopPane.add(clientFrame);
            clientFrame.setClosable(true);
            clientFrame.setIconifiable(true);
            clientFrame.setMaximizable(true);
            clientFrame.setResizable(true);
            clientFrame.setVisible(true);
            clientFrame.setSelected(true);

            // 🔹 3) REGISTRAR el frame para este cliente (esto faltaba)
            MainFrame.registerClientFrame(client, clientFrame);

        } catch (Exception ex) {
            ex.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al crear el cliente/certificado: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addClientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addClientButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
